In [32]:
%reset
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import ticker
#%matplotlib inline
df = pd.read_csv('log_longtrain.txt', sep = " ")
df

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


fsd  in_rad  conv_rad  def_rad  rep_ext  kp_ext  num_ker_pts  \
0   0.5    15.0       1.5      5.0      1.2     1.2           15   
1   0.5    15.0       1.5      5.0      1.2     1.2           15   
2   0.5    15.0       1.5      5.0      1.2     1.2           25   
3   0.5    15.0       1.5      5.0      1.2     1.2           25   
4   0.5    15.0       1.5      5.0      1.2     1.2           35   
5   0.5    15.0       1.5      5.0      1.2     1.2           35   
6   0.5    15.0       1.5      5.0      1.2     1.2           45   
7   0.5    15.0       1.5      5.0      1.2     1.2           45   
8   0.5    25.0       1.5      5.0      1.2     1.2           15   
9   0.5    25.0       1.5      5.0      1.2     1.2           15   
10  0.5    25.0       1.5      5.0      1.2     1.2           25   
11  0.5    25.0       1.5      5.0      1.2     1.2           25   
12  0.5    25.0       1.5      5.0      1.2     1.2           35   
13  0.5    25.0       1.5      5.0      1.2     1.2           35   
14  0.5    25.0       1.5      5.0      1.2     1.2           45   
15  0.5    25.0       1.5      5.0      1.2     1.2           45   
16  0.5    35.0       1.5      5.0      1.2     1.2           15   
17  0.5    35.0       1.5      5.0      1.2     1.2           15   
18  0.5    35.0       1.5      5.0      1.2     1.2           25   
19  0.5    35.0       1.5      5.0      1.2     1.2           25   
20  0.5    35.0       1.5      5.0      1.2     1.2           35   
21  0.5    35.0       1.5      5.0      1.2     1.2           35   
22  0.5    35.0       1.5      5.0      1.2     1.2           45   
23  0.5    35.0       1.5      5.0      1.2     1.2           45   

    def_fit_power  max_epoch  steps_per_epoch  ...  acc_aver acc_var  \
0             0.5         20              100  ...    0.9573  0.0003   
1             1.0         20              100  ...    0.9529  0.0005   
2             0.5         20              100  ...    0.9590  0.0004   
3             1.0         20              100  ...    0.9588  0.0002   
4             0.5         20              100  ...    0.9640  0.0002   
5             1.0         20              100  ...    0.9572  0.0005   
6             0.5         20              100  ...    0.9583  0.0006   
7             1.0         20              100  ...    0.9580  0.0005   
8             0.5         20              100  ...    0.9646  0.0002   
9             1.0         20              100  ...    0.9637  0.0001   
10            0.5         20              100  ...    0.9727  0.0001   
11            1.0         20              100  ...    0.9651  0.0001   
12            0.5         20              100  ...    0.9715  0.0001   
13            1.0         20              100  ...    0.9668  0.0003   
14            0.5         20              100  ...    0.9711  0.0001   
15            1.0         20              100  ...    0.9665  0.0003   
16            0.5         20              100  ...    0.9673  0.0001   
17            1.0         20              100  ...    0.9686  0.0002   
18            0.5         20              100  ...    0.9694  0.0001   
19            1.0         20              100  ...    0.9703  0.0000   
20            0.5         20              100  ...    0.9715  0.0001   
21            1.0         20              100  ...    0.9668  0.0003   
22            0.5         20              100  ...    0.9711  0.0001   
23            1.0         20              100  ...    0.9665  0.0003   

    mIoU_aver  IoU_other_aver  IoU_ground_aver  IoU_bui_aver  mIoU_var  \
0      69.744          75.223           75.073        58.936     0.010   
1      55.075          81.665           40.747        42.812     0.000   
2      76.546          70.473           86.436        72.729     0.006   
3      47.107          68.822           34.658        37.840     0.001   
4      41.863          71.998           19.456        34.135     0.002   
5      87.584          84.327           90.987        87.4

In [34]:
# How does IoU_other_aver, IoU_ground_aver and IoU_bui_aver change when moving from def_fit_power 0.5 to 1.0
df_fit_pow05 = df[df.index % 2 == 0]
df_fit_pow10 = df[df.index % 2 == 1]
df_fit_pow05.index = df_fit_pow05.index / 2
df_fit_pow10.index = (df_fit_pow10.index - 1) / 2
df_fit_pow_compar = pd.concat([df_fit_pow10['IoU_other_aver'] - df_fit_pow05['IoU_other_aver'],
                     df_fit_pow10['IoU_ground_aver'] - df_fit_pow05['IoU_ground_aver'], 
                     df_fit_pow10['IoU_bui_aver'] - df_fit_pow05['IoU_bui_aver']], axis=1)
df_fit_pow_compar

IoU_other_aver  IoU_ground_aver  IoU_bui_aver
0.0            6.442          -34.326       -16.124
1.0           -1.651          -51.778       -34.889
2.0           12.329           71.531        53.305
3.0            0.561          -82.524       -55.014
4.0            2.543           -1.352        -4.840
5.0            2.373           -9.843       -17.681
6.0            1.979          -36.125       -36.859
7.0            0.030           -1.039        -1.517
8.0            4.796           14.250        22.500
9.0            0.785            0.273        -1.299
10.0           1.979          -36.125       -36.859
11.0           0.030           -1.039        -1.517

In [52]:
# How does IoU_other_aver, IoU_ground_aver and IoU_bui_aver change when moving num_ker_pts through [15, 25, 35, 45]
# Every row contains comparable values - average IoU of some class, num_ker_pts is different, values of all other params are the same
df_grow_nkpts_IoU_other_aver = np.vstack([np.array(df_fit_pow05['IoU_other_aver'].iloc[0:4]),  np.array(df_fit_pow05['IoU_other_aver'].iloc[4:8]), np.array(df_fit_pow05['IoU_other_aver'].iloc[8:12])])
df_grow_nkpts_IoU_other_aver

array([[75.223, 70.473, 71.998, 77.031],
       [78.848, 82.444, 80.784, 82.795],
       [78.648, 81.213, 80.784, 82.795]])

In [53]:
# How does IoU_other_aver, IoU_ground_aver and IoU_bui_aver change when moving num_ker_pts through [15, 25, 35, 45]
df_grow_nkpts_IoU_ground_aver = np.vstack([np.array(df_fit_pow05['IoU_ground_aver'].iloc[0:4]),  np.array(df_fit_pow05['IoU_ground_aver'].iloc[4:8]), np.array(df_fit_pow05['IoU_ground_aver'].iloc[8:12])])
df_grow_nkpts_IoU_ground_aver

array([[75.073, 86.436, 19.456, 85.846],
       [88.838, 90.177, 88.981, 87.956],
       [76.511, 89.862, 88.981, 87.956]])

In [55]:
# How does IoU_other_aver, IoU_ground_aver and IoU_bui_aver change when moving num_ker_pts through [15, 25, 35, 45]
df_grow_nkpts_IoU_bui_aver = np.vstack([np.array(df_fit_pow05['IoU_bui_aver'].iloc[0:4]),  np.array(df_fit_pow05['IoU_bui_aver'].iloc[4:8]), np.array(df_fit_pow05['IoU_bui_aver'].iloc[8:12])])
df_grow_nkpts_IoU_bui_aver

array([[58.936, 72.729, 34.135, 85.849],
       [87.087, 88.384, 85.611, 80.354],
       [65.383, 87.802, 85.611, 80.354]])

In [67]:
dfar = np.array(df[['IoU_other_aver', 'IoU_ground_aver', 'IoU_bui_aver']])
dfar

array([[75.223, 75.073, 58.936],
       [81.665, 40.747, 42.812],
       [70.473, 86.436, 72.729],
       [68.822, 34.658, 37.84 ],
       [71.998, 19.456, 34.135],
       [84.327, 90.987, 87.44 ],
       [77.031, 85.846, 85.849],
       [77.592,  3.322, 30.835],
       [78.848, 88.838, 87.087],
       [81.391, 87.486, 82.247],
       [82.444, 90.177, 88.384],
       [84.817, 80.334, 70.703],
       [80.784, 88.981, 85.611],
       [82.763, 52.856, 48.752],
       [82.795, 87.956, 80.354],
       [82.825, 86.917, 78.837],
       [78.648, 76.511, 65.383],
       [83.444, 90.761, 87.883],
       [81.213, 89.862, 87.802],
       [81.998, 90.135, 86.503],
       [80.784, 88.981, 85.611],
       [82.763, 52.856, 48.752],
       [82.795, 87.956, 80.354],
       [82.825, 86.917, 78.837]])

In [82]:
in_rad_IoU_other_aver = dfar[:, 0].reshape((3,8)).transpose()
in_rad_IoU_other_aver
# Every row contains comparable values - average IoU of class Other, in_rad is different, values of all other params are the same

array([[75.223, 78.848, 78.648],
       [81.665, 81.391, 83.444],
       [70.473, 82.444, 81.213],
       [68.822, 84.817, 81.998],
       [71.998, 80.784, 80.784],
       [84.327, 82.763, 82.763],
       [77.031, 82.795, 82.795],
       [77.592, 82.825, 82.825]])

In [86]:
np.vstack([in_rad_IoU_other_aver[:,0] < in_rad_IoU_other_aver[:,1], in_rad_IoU_other_aver[:,1] < in_rad_IoU_other_aver[:,2]])

array([[ True, False,  True,  True,  True, False,  True,  True],
       [False,  True, False, False, False, False, False, False]])

In [74]:
in_rad_IoU_ground_aver = dfar[:, 1].reshape((3,8)).transpose()
in_rad_IoU_ground_aver
# Every row contains comparable values - average IoU of class Ground, in_rad is different, values of all other params are the same

array([[75.073, 88.838, 76.511],
       [40.747, 87.486, 90.761],
       [86.436, 90.177, 89.862],
       [34.658, 80.334, 90.135],
       [19.456, 88.981, 88.981],
       [90.987, 52.856, 52.856],
       [85.846, 87.956, 87.956],
       [ 3.322, 86.917, 86.917]])

In [87]:
np.vstack([in_rad_IoU_ground_aver[:,0] < in_rad_IoU_ground_aver[:,1], in_rad_IoU_ground_aver[:,1] < in_rad_IoU_ground_aver[:,2]])

array([[ True,  True,  True,  True,  True, False,  True,  True],
       [False,  True, False,  True, False, False, False, False]])

In [75]:
in_rad_IoU_bui_aver = dfar[:, 2].reshape((3,8)).transpose()
in_rad_IoU_bui_aver
# Every row contains comparable values - average IoU of class Building, in_rad is different, values of all other params are the same

array([[58.936, 87.087, 65.383],
       [42.812, 82.247, 87.883],
       [72.729, 88.384, 87.802],
       [37.84 , 70.703, 86.503],
       [34.135, 85.611, 85.611],
       [87.44 , 48.752, 48.752],
       [85.849, 80.354, 80.354],
       [30.835, 78.837, 78.837]])

In [88]:
np.vstack([in_rad_IoU_bui_aver[:,0] < in_rad_IoU_bui_aver[:,1], in_rad_IoU_bui_aver[:,1] < in_rad_IoU_bui_aver[:,2]])

array([[ True,  True,  True,  True,  True, False, False,  True],
       [False,  True, False,  True, False, False, False, False]])

In [ ]:
# As a result, I'd say that in_rad = 25 is the best value